name = "api"
main = "./api.mjs"
workers_dev = false
route = { pattern = "api.biblogos.info", custom_domain = true, zone_name = "biblogos.info" }
compatibility_date = "2022-10-01"

[build]
command = "npm install && npm run build"
